### ISSUE TITLE
[Feature Request] Save/export current waveform buffer

### ISSUE THREAD

**Issue by mpu42** [jetperch/pyjoulescope_ui#10]
When taking a waveform trace without the record option, once paused, it would be nice to be able to save out the current buffer. Maybe even have the option to save between annotation markers?

**Comment by mpu42** [comment]
Looks like this might already be implemented https://github.com/jetperch/pyjoulescope_ui/issues/6

If so, feel free to reject. The ability to export wasn't intuitive to me when I was trying to do it earlier. Could maybe improve UX.

**Comment by mliberty1** [comment]
Added in 0.9.1.
