### ISSUE TITLE
Horizontal cursor 

### ISSUE THREAD

**Issue by efox29** [jetperch/pyjoulescope_ui#101]
It might be nice to have a horizontal cursor such that the user can specify a visual aid for a threshold. Sometimes I am looking for the current to exceed a certain value. It would be nice to visually see all those points without zooming into the details (since triggering on current is not possible to my knowledge).

**Comment by mliberty1** [comment]
Hi @efox29.  Before I start asking questions, perhaps you have not yet come across horizontal markers:
![image](https://user-images.githubusercontent.com/5393422/96133622-f913bb00-0ec8-11eb-965c-be2157fd0e58.png)

This feature is now in the most recent 0.9.2 release, and it is admittedly not the most easily discoverable feature.  To add a horizontal marker, right-click (control-click on mac) on the y-axis, like this:
![image](https://user-images.githubusercontent.com/5393422/96134025-252f3c00-0ec9-11eb-9e10-1e493bfffe72.png)

Does this already do what you want?

**Comment by efox29** [comment]
Derp.

This is exactly it, I saw that menu, but when I saw single and dual markers, I just assumed, it was for the vertical (which is what I use most of the time).

Closed.
