### ISSUE TITLE
Problem installing joulescope on Windows 10

### ISSUE THREAD

**Issue by designingSparks** [jetperch/pyjoulescope_ui#107]
I get a strange error message: 'An error occurred when trying to read the source file: access is denied.'  At this point the installer is trying to extract joulescope.exe to  C:\Program Files (x86)\Joulescope. I have tried running the installer as an administrator but this doesn't help.

**Comment by mliberty1** [comment]
Hi @designingSparks : Are you trying to install the official Joulescope UI distribution available from [joulescope.com](https://www.joulescope.com/pages/downloads) or one that you created, as in #106.

**Comment by designingSparks** [comment]
Hi @mliberty1  I'm trying to install the official Joulescope UI distribution. I still have to try creating my own as described in #106.

**Comment by mliberty1** [comment]
Ok.  We have to figure out what is different about your computer.  The Joulescope UI has been installed on many, many Windows 10 machines without any issues.  Here are some things to try:

1. It's possible that the exe file was somehow corrupted.  Delete the existing installer and [download](https://www.joulescope.com/pages/downloads) a new copy.  Try to install again.
2. Are you running on a work computer administered by your IT department?  Do they have any permissions settings that restrict program installation?
3. Is the installer running from your local drive (HDD or SSD)? 
4. Are you running Win 10x64?  Note that the Joulescope UI will not run on 32-bit Windows.

**Comment by designingSparks** [comment]
Hi @mliberty1 I have tried downloading the installer again but this doesn't appear to help. I have even tried a different install location. I am running on a managed work computer but I generally don't have problems installing programs since I have admin rights. I am running the installer from my local SSD drive.

**Comment by designingSparks** [comment]
It is possible that the antivirus SW running in the background is blocking this.

**Comment by mliberty1** [comment]
Hi @designingSparks - Any updates?  Did turning off antivirus work?

**Comment by designingSparks** [comment]
I wasn't able to turn off the antivirus software but I can now build a standalone executable. It may be worth placing a standalone version of the software on the website for this reason.
