### ISSUE TITLE
Feature request: when adding dual cursors, display mAh as well

### ISSUE THREAD

**Issue by limpkin** [jetperch/pyjoulescope_ui#122]
... because dividing by 3.6 is too hard ;)

**Comment by mliberty1** [comment]
Hi @limpkin - I think that we already have this!  Check this out:

![image](https://user-images.githubusercontent.com/5393422/114270016-14730500-99d8-11eb-97de-0ffdfaa897e9.png)

You need to change the units in preferences.  Here's how:

1. Select **File** → **Preferences**
2. Set **Profile** to defaults.
3. Select **Units**.  
4. Set **charge** to **Ah**.

![image](https://user-images.githubusercontent.com/5393422/114270166-e510c800-99d8-11eb-990d-bf8edc510be1.png)

Then, the charge display on the multimeter widget, the single value widget, the control widget, the right-hand statistics on the waveform view and the dual markers should all be in Ah, not C.

Does this do what you want?

**Comment by mliberty1** [comment]
Hi @limpkin - I am following up to see if I can close this issue.  Does my response above address what you want?

**Comment by limpkin** [comment]
sorry, notifications are not working for me with github :/.
yeah of course, please close it :) thanks!!!
