### ISSUE TITLE
Configure display precision for waveform markers

### ISSUE THREAD

**Issue by mliberty1** [jetperch/pyjoulescope_ui#130]
Version: 0.9.7
Platform: All

**Description**
The waveform view always displays 6 digits for all numbers, like this:
![image](https://user-images.githubusercontent.com/5393422/122560310-779f9a00-d00e-11eb-884c-17324cfc544a.png)

The summary over the waveform shown at right also displays 6 digits.  

This takes up more room than needed if you only care to see 3 digits.  The extra precision can also detract from presentations and feel overwhelming.

**Expected behavior**
Add a configuration option that would allow the user to set the precision.  You can still leave 6 digits as the default, but then a user could configure 3 digits if that is all they want.

**Comment by atsju** [comment]
In the same way for "optionalization"an maybe linked to #144 it could be great to choose which info to display.
For example in your pricture I'm only interested into first and two last lines. The rest is only distraction for the eyes.

**Comment by mliberty1** [comment]
Added in 1.0.58.  Right-click on the waveform, **Settings** → **precision**.
