### ISSUE TITLE
OSX: Data loss while running in background

### ISSUE THREAD

**Issue by mjessome** [jetperch/pyjoulescope_ui#139]
Hello,

Joulescope UI version 0.9.10
Joulescope driver version 0.9.7

I've noticed that from time to time, when Joulescope UI is running in the background (fully occluded by other windows on my desktop), I lose a lot of data during collection. Sometimes when I switch back to the Joulescope UI it completely starts back as if it were a new collection, and other time we end up with something in the screenshot:
<img width="1113" alt="Screen Shot 2021-12-16 at 5 09 47 PM" src="https://user-images.githubusercontent.com/485012/146456339-43387d88-bb95-4c74-8c9e-1672eed85641.png">

You can see on the left there's lots of missing data, and then at about 102s, I bring it back into the foreground and collection resumes OK. As I mentioned, this issue is fairly inconsistent: sometimes I have lost data like in the screenshot, other times the timeline is empty and it seems like there is no longer a connection to the Joulescope, and sometimes nothing seems to be lost.

I've run into similar issues with a Mac application I work on losing serial connection & data when in the background. My guess here is that this is likely due to the "App Nap" feature of OSX starving pyjoulescope_ui, or stopping collection. I came across https://github.com/minrk/appnope recently which could be of service here.

**Comment by mliberty1** [comment]
It definitely looks like macOS is deciding not to give cycles to the Joulescope UI, which causes the data loss you observed.  Thanks for the pointer to the "appnope" package.  We'll take a look.  In the meantime, you have at least two options:
1. Keep the Joulescope UI window on top while capturing data.
2. Run from source add that "appnope" call at the top of [main.py](https://github.com/jetperch/pyjoulescope_ui/blob/master/joulescope_ui/main.py).
