### ISSUE TITLE
[Enhancement]: range in datasheet VS UI

### ISSUE THREAD

**Issue by atsju** [jetperch/pyjoulescope_ui#162]
### UI version

0.9.11

### Your idea

During todays measurement we needed to know the guaranteed precision for used range so we displayed range in UI. But there is no direct link between range number in UI and the datasheet.

Please consider adding a column in datasheet.
![image](https://user-images.githubusercontent.com/4628382/173780942-5b4d4c28-d9dd-4af5-ad4d-919225c93b11.png)

**Comment by mliberty1** [comment]
Thanks for the suggestion @atsju !  I can confirm that the numbering above matches what the UI displays.  Also, 7 is `off`, meaning no shunt resistor is selected.

**Comment by mliberty1** [comment]
1.0.0 now applies the current range labels to the y-axis:

![image](https://user-images.githubusercontent.com/5393422/224415077-fcbc8709-134b-498e-8d3d-66e5571e56b6.png)
