### ISSUE TITLE
[Bug]: values not computed on displayed window

### ISSUE THREAD

**Issue by atsju** [jetperch/pyjoulescope_ui#164]
### Joulescope serial number

002842

### UI version

0.9.11

### What OS are you seeing the problem on?

Windows 10

### What happened?

![image](https://user-images.githubusercontent.com/4628382/176644330-26b2bb64-4c03-4fdd-ac83-d7144536bf87.png)
We see that signal is about 6mA which is confirmed with green cursors. The mean value on the right is moving when zooming so I am expecting it to be the value of the displayed section but it's not the case.

I add some captures at different zoom levels to show how strange it is. Value even grows with less zoom when all displayed signal is lower: 
![image](https://user-images.githubusercontent.com/4628382/176655828-3086deb8-de09-418c-a7e9-0adfa672485d.png)
This "seems" OK at first glance
![image](https://user-images.githubusercontent.com/4628382/176656008-48fac667-24cd-4597-9d3e-960c7caefc4f.png)
This also
![image](https://user-images.githubusercontent.com/4628382/176656135-cf502321-dd4a-43e9-8a83-0328a40e87d5.png)

### What was expected?

The value on the right should be about the same as between green cursors. I expect values on the right to be computed on displayed section of measurement.

### How to reproduce?

1. Measure some AC signal (30s window)
2. zoom in the window
3. check mean values versus displayed signal

**Comment by atsju** [comment]
I understand. So any zoom level fine enough to not display the red min/max lines would take more samples than what is on screen.
Seems coherent with what I observed. Thank you for prompt support.

I'm impatient to test the improved 1.0.0 :innocent:

**Comment by mliberty1** [comment]
This should be fixed in 1.0.0.  When zoomed in this far, single samples make a difference between the right-hand display and the dual markers.  However, with a little care in positioning, we now get the same answer:

![image](https://user-images.githubusercontent.com/5393422/224413408-dff4bd5d-62ee-4129-81a8-39b975027280.png)
