### ISSUE TITLE
[Bug]: Incorrect scaling in live view

### ISSUE THREAD

**Issue by NevynUK** [jetperch/pyjoulescope_ui#168]
### Joulescope serial number

001736

### UI version

0.10.8

### What OS are you seeing the problem on?

macOS 13 amd64

### What happened?

I have connected a Meadow (microcontroller board) using the USB powered hub through to a MacBook Pro.  This board has nothing running except the OS so I am expecting low current draw.  Running the UI connected to the Joulescope shows the following:

![LiveData](https://user-images.githubusercontent.com/8407073/199040366-02583624-54d5-438e-aeb9-67fb37d1cb64.png)

Note the scale is 0 - 5A and the statistics also reflect this:

![LiveDataStatistics](https://user-images.githubusercontent.com/8407073/199040539-5764f61c-661a-4bfb-a927-7a2965282a5b.png)

Note that the multimeter view is showing the correct average , minimum and maximum values.

### What was expected?

I am expected the board to average about 130mA with periodic peaks.  The following is a JLS file from a 5 minute run captured using the Python capture.py script:

![ReadImportedFile](https://user-images.githubusercontent.com/8407073/199041074-77b7caef-bcce-407f-b133-c94b121104de.png)

This looks correct.

### How to reproduce?

1. ... Connect a low current microcontroller board to a computer through a JS110.
2. ... Start the Joulescope UI

**Comment by mliberty1** [comment]
Thanks @NevynUK !  It sounds like the current range change filter is not being applied correctly.  I was able to duplicate the issue.

Here is a capture of the original JS110 EVK using 0.9.11:
![image](https://user-images.githubusercontent.com/5393422/199043999-7c3cf055-bc9a-4705-9cc9-81162a82b659.png)

And the same capture using 0.10.8:
![image](https://user-images.githubusercontent.com/5393422/199044432-50dcc93d-5e6c-4960-b070-ab250b2f341a.png)

Here are the current range settings:
![image](https://user-images.githubusercontent.com/5393422/199044651-6bfe24dd-9531-4d31-b8da-2a41efb4c1d5.png)

We'll be investigating today!

**Comment by mliberty1** [comment]
I tracked down the issue, which is actually in the joulescope driver [js110_sample_processor](https://github.com/jetperch/joulescope_driver/blob/main/src/js110_sample_processor.c).  The code was not correctly respecting the "n" and "m" samples_window settings.  We should have a new Joulescope UI release tomorrow.

**Comment by NevynUK** [comment]
Thank you for the update.  Look forward to using the new release.
