### ISSUE TITLE
[Bug]: Unhandled exception in script after version update installer 0.10.10 (Win10)

### ISSUE THREAD

**Issue by MATTERealise** [jetperch/pyjoulescope_ui#173]
### Joulescope serial number

000031

### UI version

0.10.9

### What OS are you seeing the problem on?

Windows 10

### What happened?

UI failed to open. Error message when first tried to open JS UI after upgrading to 10.10, using the checkbox for "open Joulescope UI" at the end of the installer process:
![image](https://user-images.githubusercontent.com/87368422/201069794-e9ca7359-f029-40a3-8226-b74609019d4e.png)

 > Traceback (most recent call last):
>   File "joulescope_ui\__main__.py", line 18, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "joulescope\__init__.py", line 23, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "joulescope\v1\__init__.py", line 15, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "joulescope\v1\driver.py", line 20, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "joulescope\v1\device.py", line 18, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "joulescope\view.py", line 16, in <module>
>   File "joulescope\v0\stream_buffer.pyx", line 31, in init joulescope.v0.stream_buffer
>   File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
>   File "psutil\__init__.py", line 241, in <module>
> ImportError: version conflict: 'C:\\Program Files (x86)\\Joulescope\\psutil\\_psutil_windows.cp310-win_amd64.pyd' C extension module was built for another version of psutil (5.9.3 instead of 5.9.4); you may try to 'pip uninstall psutil', manually remove C:\Program Files (x86)\Joulescope\psutil\_psutil_windows.cp310-win_amd64.pyd or clean the virtual env somehow, then reinstall

### What was expected?

UI should open :smile:

### How to reproduce?

1. follow the built-in upgrade installer from the UI on Win10
2. check the "open Joulescope UI" box on the last screen and click "ok" or whatever that button was to proceed.

### Extra information

I'll try opening again but I'm fairly sure you want to address this regardless of whether it works second time round. Will update!

**Comment by MATTERealise** [comment]
Still fails to open from Start menu.

**Comment by MATTERealise** [comment]
Reverted to 10.9 and opens fine.

OS info, in case it helps reproduce (just had a windows update yesterday)

> Edition	Windows 10 Pro
> Version	21H1
> Installed on	‎12/‎07/‎2021
> OS build	19043.2251
> Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by mliberty1** [comment]
Thanks for reporting this @MATTERealise .  It looks like the 0.10.10 installer is not removing the file:

    "C:\Program Files (x86)\Joulescope\psutil\_psutil_windows.cp310-win_amd64.pyd"

If you manually delete this file, the Joulescope UI 0.10.10 runs correctly.

Alternatively, you can uninstall and then reinstall the 0.10.10 Joulescope UI.  The uninstall process does correctly delete this file, but apparently the upgrade process does not.

**Comment by MATTERealise** [comment]
I'm happy with 10.9 until 10.11 gets released! Thanks for fast dev'ing!

**Comment by MATTERealise** [comment]
10.11 in-UI update worked perfectly, thanks!
