### ISSUE TITLE
Oscilloscope view of JLSv2 | Statistics for dual marker add delta energy

### ISSUE THREAD

**Issue by ClimbTheWorld** [jetperch/pyjoulescope_ui#177]
### UI version

0.10.9

### Your idea

Hi,
When openening a JLSv2 file in the oscilloscope view and using a marker the delta energy is not shown, where it is in JLSv1.

**Comment by mliberty1** [comment]
Thanks for reporting this issue, @ClimbTheWorld .  We are currently working on a major Joulescope UI update, and we will ensure that this works in the updated UI.  The current plan is to have an alpha version in early February (~2 weeks from today).

The workaround for 0.10.x is to manually multiply the average power by the total time.

**Comment by mliberty1** [comment]
Confirm fixed in 1.0.14 alpha (beta pending ongoing testing).  Download here:

https://download.joulescope.com/joulescope_install/index_v2.html
