### ISSUE TITLE
[Feature Request] Time delta numbers only show in engineering notation

### ISSUE THREAD

**Issue by efox29** [jetperch/pyjoulescope_ui#19]
When zooming into a waveform and measuring between two points, delta is represented in scientific notation. It would be beneficial to use engineering notation since that is the notation that we use. 

![Capture](https://user-images.githubusercontent.com/304290/64209507-b5015a80-ce6e-11e9-83d9-832b2d8c759a.PNG)

**Comment by mliberty1** [comment]
Agreed.  This feature is loosely related to [this request](https://forum.joulescope.com/t/x-axis-division-labels/126) from the Joulescope forum.

**Comment by mliberty1** [comment]
Fixed in 2a43a82 which will be included in the next release:
![image](https://user-images.githubusercontent.com/5393422/64286567-c78d9980-cf2b-11e9-8641-8665daccf99a.png)
