### ISSUE TITLE
python 3.10+ support

### ISSUE THREAD

**Issue by zod6** [jetperch/pyjoulescope_ui#194]
### Joulescope model

JS110

### UI version

0.10.13

### Your idea

currently PySide6==6.3.2 is needed which requires python<3.10.
From Debian Bookworm minimum python version available is 3.10.

When changing to PySide6==6.5.0 in requirements.txt, it compiles with python 3.11, runs and haven't seen any problems yet.
So please update PySide6 version requirement if possible.

// why not joulescope_ui 1.x? personal preference :)

### Does your idea concern a specific OS?

Debian Bookworm on amd64

**Comment by mliberty1** [comment]
Hi @zod6 - With the first stable 1.0.x release, we no longer support the 0.9.x or 0.10.x releases.  I highly encourage you to give 1.x a chance.  If you have constructive feedback about anything you miss from 0.10.x, I would definitely like to hear it here or on the [forum](https://forum.joulescope.com/).

If you insist on using 0.10.x, I recommend that you run from the release/0.10 branch which contains fixes that we never released as we were focused on 1.0.x.  Something like this should work:

    git clone git@github.com:jetperch/pyjoulescope_ui.git
    cd pyjoulescope_ui
    git checkout release/0.10
    python3 -m venv ~/venv/joulescope_ui
    . ~/venv/joulescope_ui/bin/activate
    python3 -m pip install -r requirements.txt
    python3 -m pip install -U PySide6
    python3 setup.py sdist
    python3 -m pip install --no-dependencies ./dist/joulescope_ui*.tar.gz

Then, whenever you want to run the Joulescope UI:

     . ~/venv/joulescope_ui/bin/activate
    python3 -m joulescope_ui

These instructions are untested and likely contain some errors.
