### ISSUE TITLE
Save image to file doesn't save

### ISSUE THREAD

**Issue by romain145** [jetperch/pyjoulescope_ui#196]
### Joulescope model

JS110

### UI version

1.0.22

### What OS are you seeing the problem on?

Windows 10

### What happened?

When using the "save image to file" the file is not saved if the image is renamed and the ".png" extension is omitted.
There are no errors, and the file is simply not saved (not even without the extension).
Related to #81

### What was expected?

.png extension should be automatically appended if missing from the file name

### How to reproduce?

1. Right click -> save image to file
2. Rename the file, don't put an extension
3. Save the file
4. The file is nowhere to be found

**Comment by mliberty1** [comment]
Thank you for reporting this @romain145 .  The fix is already in main, and it will be in the upcoming 1.0.23 UI release.
