### ISSUE TITLE
Joulescope UI 1.0.31 is not creating an .exe

### ISSUE THREAD

**Issue by chriszylstra** [jetperch/pyjoulescope_ui#236]
### Joulescope model

JS220

### UI version

1.0.31

### What OS are you seeing the problem on?

Windows 11

### What happened?

When I update the UI to the latest stable 1.0.31 I get an installation error shown below:

![image](https://github.com/jetperch/pyjoulescope_ui/assets/13257196/d1f6e808-720b-4a84-a1d3-22c429eb8d26)

The installer is not creating the joulescope.exe in the filepath C:\Program Files\Joulescope\joulescope.exe

![image](https://github.com/jetperch/pyjoulescope_ui/assets/13257196/cb2cdbdd-5785-4923-909e-f7b3e2df5610)

The problem is solved by running the old installer for v1.0.30 and I can use the software

### What was expected?

I was expecting the installer to create the joulescope.exe at the file location C:\Program Files\Joulescope\joulescope.exe
![image](https://github.com/jetperch/pyjoulescope_ui/assets/13257196/39d284ef-ff9d-4fbd-8a7e-e46cc409146c)

### How to reproduce?

1. Run the joulescope_step_1_0_31.exe
2. Observe the filestructure C:\Program Files\Joulescope\

### Extra information

I am not uninstalling between tests. Only running the old 1.0.30 and new 1.0.31 Joulsescope UI installation file.

**Comment by chriszylstra** [comment]
Just reading through the open/closed issues and releases to see if there are other's having this issue and I notice this:
![image](https://github.com/jetperch/pyjoulescope_ui/assets/13257196/a8e9ba41-dfdb-4f51-87c0-adfd2f8dc3d4)

so I'll test 1.0.37 beta and see if this comment is related

**Comment by mliberty1** [comment]
Hi @chriszylstra - Recent anti-virus software changes flagged joulescope.exe as malicious.  It is likely that it quarantined this file. 
 See the [forum](https://forum.joulescope.com/t/joulescope-ui-1-0-36-flagged-by-anti-virus-software/673) for the discussion.  If you check the antivirus history, you should be restore this file from quarantine.  Microsoft's Windows Defender is now fixed, so update your antivirus definitions.

**Comment by chriszylstra** [comment]
Good call @mliberty1 this was the issue I faced. Thanks for the feedback. I read the forum post you linked.

We are using SentinelOne virus scanner and it got flagged as positive threat. 
![image](https://github.com/jetperch/pyjoulescope_ui/assets/13257196/84c9d3a5-3adb-400b-ba80-7b83de06e766)

All fixed now though, i'm not sure if you would like to submit SentinelOne for false postive analysis as well, but thank you for the support. 

-cz.

**Comment by mliberty1** [comment]
We are already working on an alternate way to distribute the Joulescope UI using Nuitka.  The results are already much better according to [VirusTotal](https://www.virustotal.com/gui/file/23d15e82dffe60fedd021542980eac4e272e401ee4f829f2f1e113404d58c50a?nocache=1).

Since we will be changing this drastically, no need to submit the existing exe to SentinalOne.
