### ISSUE TITLE
Calibration widget assets not being installed

### ISSUE THREAD

**Issue by florolf** [jetperch/pyjoulescope_ui#242]
### Joulescope model

JS220

### UI version

other

### What OS are you seeing the problem on?

Linux Ubuntu amd64 (PC)

### What happened?

When trying to open the calibration widget, the UI crashes because it cannot find `current_offset.png` (and `voltage_offset.png`).

They are present in the source, but do not get installed into the appropriate paths when `pip install` is executed.

### What was expected?

The referenced files should get installed and the UI should not crash.

### How to reproduce?

1. Install the UI, for example using `python -m pip install -U --upgrade-strategy=eager joulescope_ui`
2. Attach a JS220 and start the UI
3. Try opening the calibration widget

**Comment by mliberty1** [comment]
Fixed in 1.0.46
