### ISSUE TITLE
Wishlist - toolbar button for toggling the min/max lines

### ISSUE THREAD

**Issue by jamesl-dm** [jetperch/pyjoulescope_ui#28]
One of the most frequent operations for me is turning the min/max lines off as required. They are super-handy when you need to see the peaks, and super irritating when you don't. It would be nice if the toggle for them wasn't buried in the settings menu - maybe a hotkey or toolbar button?

**Comment by mliberty1** [comment]
Noted!  We are currently architecting a change to how the Joulescope UI manages preferences.  We will add this feature, likely as a right-click context menu option.

**Comment by jamesl-dm** [comment]
Thanks!

**Comment by mliberty1** [comment]
Added "Waveform Control" widget to 0.7.0, which includes Min/Max lines as shown here:
![waveform_control](https://user-images.githubusercontent.com/5393422/70170340-8166e400-169a-11ea-9108-324f8e575ab9.png)
