### ISSUE TITLE
Ui_DeveloperDockWidget is missing

### ISSUE THREAD

**Issue by ferret-guy** [jetperch/pyjoulescope_ui#3]
When trying to run from source I found that the following widgets are missing:

- Ui_DeveloperDockWidget
- Ui_ErrorWindow
- Ui_mainWindow
- Ui_ControlDockWidget

It looks like they might be in the .gitignore under these files:

- control_widget.py
- developer_widget.py
- error_window.py
- main_window.py

**Comment by mliberty1** [comment]
These missing files are expected since they are generated from the corresponding Qt ".ui".  For now, run:

    python3 setup.py sdist

which generates these files.  I will investigate and update the README with the recommended way of generating these files for development.

**Comment by ferret-guy** [comment]
Thanks for the quick response! I am unfamiliar with Qt so I appreciate the help.

**Comment by mliberty1** [comment]
No worries!  I looked and I haven't documented this.  "compiling" before running Python code is very unusual, so I need to figure out how to make this easy...

**Comment by mliberty1** [comment]
I added a separate "qt" command so that you can just generate (or regenerated) the Qt resource files and the Qt python files from the ".ui" files.  Run:

    python3 setup.py qt

This change is in develop now, and will be merged into master in the next release.
