### ISSUE TITLE
Save annotations applied to JLS recordings

### ISSUE THREAD

**Issue by mliberty1** [jetperch/pyjoulescope_ui#41]
Affects: All platforms
Versions: 0.7.0

The Joulescope UI records live Joulescope data to JLS files.  The user can then open the JLS files using the Joulescope UI, explore the data, and add annotations.  The UI should allow the user to save these annotations and last view range alongside the original JLS file.  When the JLS file is opened again, the UI should restore the last view range and add all annotations.

The annotations are currently limited to single markers and dual markers, but this feature would apply to any future annotations added to the UI.

**Comment by raveslave** [comment]
any updates?

**Comment by mliberty1** [comment]
None yet, but it's still on the list!

**Comment by mliberty1** [comment]
Fixed in [v0.9.7](https://github.com/jetperch/pyjoulescope_ui/releases/tag/v0.9.7).
