### ISSUE TITLE
[Feature Request] Keyboard annotation interaction

### ISSUE THREAD

**Issue by mpu42** [jetperch/pyjoulescope_ui#9]
Would like to see annotations be dropped with the keyboard as in the Saleae Logic software:

Pressing the number keys attaches measurement markers to the cursor, dropped when clicked. Pairs are attached to 1 and 2, 3 and 4, and so on. Maybe 1 drops the single annotation, and 2 and 3 drop the dual? Something like that.

**Comment by mliberty1** [comment]
Pressing the number key brings the marker into view.  For single markers, it pans the view so that the marker is in the middle.  For dual markers it both pans and zooms to show both markers.

**Comment by mliberty1** [comment]
Added in 0.9.1.
