### ISSUE TITLE
Remember last saved location

### ISSUE THREAD

**Issue by efox29** [jetperch/pyjoulescope_ui#92]
When exporting the data, the default path My Documents/joulescope, but I may want to save to another location with multiple exports, and I would have to navigate to the path each time. 

Would be great if when saving, the last path is remembered.

**Comment by mliberty1** [comment]
The 0.9.2 UI has a data_path preference that determines the path for all JLS loads & saves:
![image](https://user-images.githubusercontent.com/5393422/90768844-4c98cc80-e2bd-11ea-93f5-e18987f3462c.png)

I think that this feature request is to add another preference, perhaps "data_path_type" as one of:
* "Most recently saved": update the load/save path whenever you save a JLS file 
* "Most recently used": update the load/save path whenever you load or save a JLS file
* "data_path": Always use the configured path.

What do you think?

**Comment by mliberty1** [comment]
Added in 0.9.3.
