### ISSUE TITLE
Joulescope UI version >=0.9.0 creates compatibility issues on linux

### ISSUE THREAD

**Issue by nithinn86** [jetperch/pyjoulescope_ui#95]
I had Joulescope UI version 0.8.16 running on my Ubuntu 18.04. The UI worked perfectly fine.
But when I try launching Joulescope UI versions >=0.9.0 using the 'joulescope_launcher', it throws the following error:

```
[3903] Error loading Python lib '/home/hputaf/Downloads/joulescope_0_9_2/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/hputaf/Downloads/joulescope_0_9_2/libpython3.8.so.1.0)
```

The earlier versions of Joulescope UI seems to have 'libpython3.6m.so.1.0'.
Please note that GLIBC_2.29 is not available on 18.04, I will either have to get it compiled or upgrade my OS, both of which does not make sense to me.
Could you please provide a solution ?

**Comment by mliberty1** [comment]
For the latest 0.9.2 release, we migrated from Ubuntu 18.04 LTS to Ubuntu 20.04 LTS.  We looked into having better distributions using Flatpak (issue #79), but the dependencies make this difficult.  For now, our recommendations are:
1. Upgrade to Ubuntu 20.04 LTS
2. Install from pypi using pip3
3. Run from source

I see issue #96 which is preventing (2) and (3), and I will address that next.
